CREATE TABLE Branch(
  BranchID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  BranchName VARCHAR(100) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  Phone VARCHAR(15) NOT NULL
  );

CREATE TABLE VehicleType(
  TypeID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  TypeName VARCHAR(50) NOT NULL
  );

CREATE TABLE Vehicle(
  VehicleID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  LicensePlate VARCHAR(10) UNIQUE NOT NULL,
  Make VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Year INT UNSIGNED NOT NULL,
  Color VARCHAR(20),
  DailyRentalRate DECIMAL(10,2) UNSIGNED NOT NULL,
  CurrentMileage INT UNSIGNED NOT NULL,
  VehicleTypeID INT UNSIGNED NOT NULL,
  RentalBranchID INT UNSIGNED NOT NULL,
  FOREIGN KEY (VehicleTypeID) REFERENCES VehicleType(TypeID),
  FOREIGN KEY (RentalBranchID) REFERENCES Branch(BranchID)
  );

CREATE TABLE MaintenanceStaff(
  StaffID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  OfficeNumber VARCHAR(10) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  Email VARCHAR(100),
  BranchContactInfo INT UNSIGNED NOT NULL,
  FOREIGN KEY (BranchContactInfo) REFERENCES Branch(BranchID)
  );

CREATE TABLE Customers(
  CustomerID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  Email VARCHAR(100),
  DriverLicenseNum VARCHAR(20) UNIQUE NOT NULL,
  LicenseExpDate DATE NOT NULL
  );

CREATE TABLE RentalAgreement(
  RentalAgreementID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CustomerID INT UNSIGNED NOT NULL,
  VehicleID INT UNSIGNED NOT NULL,
  ScheduledPickup DATETIME NOT NULL,
  ScheduledReturn DATETIME NOT NULL, 
  ActualPickup DATETIME,
  ActualReturn DATETIME,
  EstimatedCost DECIMAL(10,2) UNSIGNED NOT NULL,
  ActualCost DECIMAL(10,2) UNSIGNED,
  Status VARCHAR(20) NOT NULL,
  PickupBranchID INT UNSIGNED NOT NULL,
  ReturnBranchID INT UNSIGNED NOT NULL,
  FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID),
  FOREIGN KEY (PickupBranchID) REFERENCES Branch(BranchID),
  FOREIGN KEY (ReturnBranchID) REFERENCES Branch(BranchID)
  );

CREATE TABLE MaintenanceRecords (
  RecordID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  VehicleID INT UNSIGNED NOT NULL,
  ReportingCustomerID INT UNSIGNED,
  StaffID INT UNSIGNED NOT NULL,
  IssueType VARCHAR(100) NOT NULL,
  Description TEXT,
  Status VARCHAR(20) NOT NULL,
  DateReported DATETIME NOT NULL,
  DateResolved DATETIME,
  Notes TEXT,
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID),
  FOREIGN KEY (ReportingCustomerID) REFERENCES Customers(CustomerID),
  FOREIGN KEY (StaffID) REFERENCES MaintenanceStaff(StaffID)
  );


  
  
  
  
